global:
  env : "dev"
  region : "us-east-1"
  # PUBLIC SUBNETS
  subnet_ids : ["subnet-0265ecca4c844fcad", "	subnet-0f7edbfdab05b5f5d", "subnet-0e326cdf17e8bc2fa"]
  vpc_id : "vpc-0d75387bb3c5f98fc"
  container_port : "8080"
  domain_name: "{{{PUT_HERE_sample_DNS}}}"
  alb_name: "sample-dev-alb"
  load_balancer_type : "application"
  path : "/"
  create_attachment : "false"
  tags:
    documentation : "DOC_URL"
    managed_by : "terraform"
    repository: "GITHUB_REPO"