global:
  env : "dev"
  region : "us-east-1"
  # ====== PUBLIC SUBNETS ====== #
  subnet_ids : ["{{SUBNET_ID_1}}", "{{SUBNET_ID_2}}", "{{SUBNET_ID_3}}"]
  vpc_id : "{{VPC_ID}}"
  container_port : "8080"
  domain_name: "{{{PUT_HERE_sample_DNS}}}"
  alb_name: "sample-dev-alb"
  load_balancer_type : "application"
  path : "/"
  create_attachment : "false"
  tags:
    documentation : "DOC_URL"
    managed_by : "terraform"
    repository: "GITHUB_REPO"