global:
  env : "dev"
  name : "my-cert"
  region : "us-east-1"
  account_name : "development"
  managed_by : "terraform"
  domain_name : "{{{PUT_HERE_sample_DNS}}}"
  subject_alternative_names : ["*.{{{PUT_HERE_sample_DNS}}}"]
  tags:
    documentation : "DOC_URL"
    managed_by : "terraform"
    repository: "GITHUB_REPO"