global:
  name : "sample-vpc"
  env : "dev"
  region: "us-east-1"
  vpc_cidr: "10.0.0.0/16"
  private_subnet_names: ["My Private Subnet 1", "My Private Subnet 2", "My Private Subnet 3"]
  public_subnet_names: ["My Public Subnet 1", "My Public Subnet 2", "My Public Subnet 3"]
  tags:
    documentation : "DOC_URL"
    managed_by : "terraform"
    repository: "GITHUB_REPO"