global:
  env: "dev"
  cluster_name: "sample-ecs"
  repository: "GITHUB_REPO"
  region: "us-east-1"
  vpc_id: "vpc-0d75387bb3c5f98fc"
  account_id: "611088767118"
  subnet_ids: # PRIVATE SUBNETS
    - "subnet-0265ecca4c844fcad"
    - "subnet-0f7edbfdab05b5f5d"
    - "subnet-0e326cdf17e8bc2fa"
  alb: sample-dev-alb
  documentation : "DOC_URL"


microservices:
  # front_end:
  #   service_name: "app1"
  #   path: ["/app1"]
  #   health_check_path: "/"
  #   port: 80
  sample_api:
    service_name: "sample-api"
    path: ["/sample_/*"]
    health_check_path: "/sample/healthcheck"
    port: 5028
    desired_count: 2
    container_cpu: 128
    container_memory: 256