global:
  env : "dev"
  region : "us-east-1"
  vpc_id : "{{VPC_ID}}"
  # PUBLIC SUBNETS
  subnet_ids : ["{{SUBNET_ID_1}}", "{{SUBNET_ID_2}}", "{{SUBNET_ID_3}}"]
  documentation : "DOC_URL"
  repository: "GITHUB_REPO"

databases:
  sample:
    name: sample
    port: 5432
    engine: postgres
    version: 16.2
    instance: "db.t3.micro"
    storage: 20
    username: sample
    parameter_group_name: "default.postgres16"