name: dev - ecs terraform

on:
  workflow_dispatch:
    inputs:
      deploy:
        description: 'Deploy resources!'
        type: boolean
        required: false
        default: false
      destroy:
        description: 'WARNING: destroy resources?'
        type: boolean
        required: false
        default: false


env:
  TF_DIRECTORY: 'ecs'
  ENVIRONMENT: 'development'
  
jobs:
  terraform:
    uses: ./.github/workflows/tf.yaml
    secrets: inherit
    with:
      deploy: ${{ inputs.deploy }}
      destroy: ${{ inputs.destroy }}
      tf_directory: ecs
      environment: development